apiVersion: tekton.dev/v1beta1
kind: task
metadata:
  name: run-python-tests
  namespace: mlops
spec:
  steps:
    - name: run-tests
      image: python:3.12
      script: |
        #!/bin/bash
        set -e
        pip install -r requirements.txt
        pytest src/tests
        