apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-python-tests
  namespace: mlops
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: python:3.12
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        pip install -r requirements.txt
        pytest src/tests