apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mlops-pipeline
  namespace: mlops
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
      type: string
      description: Git repository URL
    - name: git-revision
      type: string
      description: Git revision to use
      default: "main"
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params: 
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
    - name: run-tests
      runAfter:
        - fetch-repository
      taskRef:
        name: run-python-tests
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: train-model
      runAfter:
        - run-tests
      taskRef:
        name: train-ml-model
      workspaces:
        - name: source
          workspace: shared-workspace